include: package:flutter_lints/flutter.yaml
linter:
  rules:
    # overridden_fields: false
    # Don't override fields: false
    # annotate_overrides: false
    # void_checks: false
    # sized_box_for_whitespace: false
    # avoid_single_cascade_in_expression_statements: false
    # file_names: false
    # sort_pub_dependencies: false
    # prefer_final_locals: false
    use_super_parameters: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test"
  # errors:
  # invalid_annotation_target: ignore
