name: dab_online_radio
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_inset_box_shadow: ^1.0.8
  percent_indicator: ^4.2.2
  curved_navigation_bar: ^1.0.3
  just_audio: ^0.9.34
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  dartz: ^0.10.1
  # freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  go_router: ^10.1.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  isar_generator: ^3.1.0+1
  freezed: ^2.4.1



flutter:

  uses-material-design: true

  assets:
    - assets/images/


    
    
                                      